GOOGLE_CLIENT: "405722211943-rjqanhq82eot2s6fts6hbm13m3bfo6ob.apps.googleusercontent.com"
GOOGLE_SECRET: "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"

NAVER_CLIENT: "JBLInZnlGFK9j1rgkpLX"
NAVER_SECRET: "7yw_Xt0ITS"
