spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
#  security:
#    user:
#      name: username
#      password: password


logging:
  level:
    org.hibernate.sql: debug
