server:
  port: 8888

spring:
  application:
    name: config-server
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Gothax/spring-study
          search-paths: msa_ecommerce

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh